Repository NREL/ditto, pull requests merged in 2018-06, with the labels that each got.

#111 Add network protectors
  ditto/models/line.py
  ditto/models/wire.py
Labels: API Modification Request

#114 Replace fuse_limit with interrupting_rating in wire model (more generic)
  ditto/models/wire.py
Labels: API Modification Request

#116 Opendss writer bugfixes
  ditto/writers/opendss/write.py
Labels: BugFix

#113 Opendss writer feeders
  ditto/metrics/network_analysis.py
  ditto/network/network.py
  ditto/readers/cyme/read.py
  ditto/writers/demo/write.py
  ditto/writers/opendss/write.py
Labels: enhancement

#112 Add network protector support for cyme reader
  ditto/readers/cyme/read.py
  tests/data/ditto-validation/cyme/network_protectors/equipment.txt
  tests/data/ditto-validation/cyme/network_protectors/load.txt
  tests/data/ditto-validation/cyme/network_protectors/network.txt
  tests/test_cyme_reader.py
Labels: New Feature Request

#106 Add replace_first_switch_with_recloser
  ditto/modify/system_structure.py
Labels: New Feature Request

#125 Opendss disabled obj
  ditto/readers/opendss/read.py
  tests/data/ditto-validation/opendss/disabled_objects/IEEELineCodes.dss
  tests/data/ditto-validation/opendss/disabled_objects/buscoord.dss
  tests/data/ditto-validation/opendss/disabled_objects/master.dss
  tests/test_opendss_reader.py
Labels: BugFix

#126 Bugfix switching devices cyme reader
  ditto/readers/cyme/read.py
  tests/data/ditto-validation/cyme/breakers/equipment.txt
  tests/data/ditto-validation/cyme/breakers/load.txt
  tests/data/ditto-validation/cyme/breakers/network.txt
  tests/data/ditto-validation/cyme/switches/equipment.txt
  tests/data/ditto-validation/cyme/switches/load.txt
  tests/data/ditto-validation/cyme/switches/network.txt
  tests/test_cyme_reader.py
Labels: BugFix

#129 Use encoding in open for README.md
  setup.py
Labels: BugFix

#128 Update setup.py with traitlets in install_requires
  setup.py
Labels: High Priority

#131 Add safety checks for Carson equation
  ditto/readers/abstract_reader.py
Labels: BugFix
