Repository NREL/ditto, pull requests merged in 2018-09, with the labels that each got.

#182 Regulators pv cyme
  ditto/metrics/network_analysis.py
  ditto/models/photovoltaic.py
  ditto/modify/system_structure.py
  ditto/readers/abstract_reader.py
  ditto/readers/cyme/read.py
  ditto/writers/cyme/write.py
  ditto/writers/opendss/write.py
Labels: enhancement

#181 Export underground lines opendss
  ditto/models/wire.py
  ditto/writers/opendss/write.py
  tests/test_opendss_writer.py
Labels: API Modification Request, enhancement

#184 Gld bug fixes
  ditto/formats/gridlabd/schema.json
  ditto/readers/gridlabd/read.py
  ditto/writers/opendss/write.py
Labels: BugFix

#186 Capacitor bugfix and added storage reader in CYME
  ditto/models/storage.py
  ditto/readers/cyme/read.py
Labels: BugFix, enhancement

#187 Improve doc
  README.md
  docs/img/Test4Node.jpg
  docs/readme.md
Labels: documentation
