Repository NREL/ditto, pull requests merged in 2018-05, with the labels that each got.

#71 Cyme to opendss bugfix
  ditto/readers/cyme/read.py
  ditto/writers/opendss/write.py
Labels: BugFix

#72 Reorder redirects and only redirect non empty files
  ditto/writers/opendss/write.py
Labels: BugFix, enhancement

#73 Handle condID_N and condID_N1
  ditto/readers/cyme/read.py
Labels: BugFix

#76 Change names and use dict
  ditto/writers/opendss/write.py
Labels: enhancement

#81 Demo reader
  ditto/cli.py
  ditto/converter.py
  ditto/readers/demo/__init__.py
  ditto/readers/demo/read.py
  ditto/writers/demo/__init__.py
  ditto/writers/demo/write.py
  setup.py
  tests/data/small_cases/demo/demo.txt
  tests/test_demo_to_gridlabd.py
Labels: New Parser

#79 Add examples
  examples/README.md
  examples/epri_j1_opendss_to_cyme.json
  examples/epri_j1_opendss_to_cyme.py
  examples/ieee_123node_cyme_to_opendss.json
  examples/ieee_123node_cyme_to_opendss.py
  examples/ieee_123node_gridlabd_to_opendss.py
  examples/ieee_8500_opendss_to_cyme.json
  examples/ieee_8500_opendss_to_cyme.py
  tests/data/big_cases/cyme/ieee_123node/equipment.txt
  tests/data/big_cases/cyme/ieee_123node/load.txt
  tests/data/big_cases/cyme/ieee_123node/network.txt
  tests/data/big_cases/gridlabd/ieee_123node/123_node.glm
  tests/data/big_cases/opendss/epri_j1/LoadShapes_mod.dss
  tests/data/big_cases/opendss/epri_j1/LoadsInd.dss
  tests/data/big_cases/opendss/epri_j1/buscoords.dss
  tests/data/big_cases/opendss/epri_j1/capacitors.dss
  tests/data/big_cases/opendss/epri_j1/linecodes.dss
  tests/data/big_cases/opendss/epri_j1/lines.dss
  tests/data/big_cases/opendss/epri_j1/master.dss
  tests/data/big_cases/opendss/epri_j1/monitors.dss
  tests/data/big_cases/opendss/epri_j1/regulators.dss
  tests/data/big_cases/opendss/epri_j1/services.dss
  tests/data/big_cases/opendss/epri_j1/substation.dss
  tests/data/big_cases/opendss/epri_j1/transformers.dss
  tests/data/big_cases/opendss/ieee_8500node/CapControls.DSS
  tests/data/big_cases/opendss/ieee_8500node/Capacitors.dss
  tests/data/big_cases/opendss/ieee_8500node/CloudTransient.dss
  tests/data/big_cases/opendss/ieee_8500node/Feeder_Loads.dss
  tests/data/big_cases/opendss/ieee_8500node/Fuses.DSS
  tests/data/big_cases/opendss/ieee_8500node/Generators.dss
  tests/data/big_cases/opendss/ieee_8500node/LineCodes.dss
  tests/data/big_cases/opendss/ieee_8500node/LineCodes2.DSS
  tests/data/big_cases/opendss/ieee_8500node/LineGeometry.dss
  tests/data/big_cases/opendss/ieee_8500node/Lines-Geometry.dss
  tests/data/big_cases/opendss/ieee_8500node/Lines.dss
  tests/data/big_cases/opendss/ieee_8500node/LoadXfmrCodes.dss
  tests/data/big_cases/opendss/ieee_8500node/LoadXfmrs.dss
  tests/data/big_cases/opendss/ieee_8500node/Loads.dss
  tests/data/big_cases/opendss/ieee_8500node/Master-unbal.dss
  tests/data/big_cases/opendss/ieee_8500node/Normalized-1s-2900-pts.CSV
  tests/data/big_cases/opendss/ieee_8500node/P174_Run_360kW_PV.DSS
  tests/data/big_cases/opendss/ieee_8500node/P174_Run_Voltage_Profile.DSS
  tests/data/big_cases/opendss/ieee_8500node/Regulators.dss
  tests/data/big_cases/opendss/ieee_8500node/Run_8500Node.dss
  tests/data/big_cases/opendss/ieee_8500node/Run_8500Node_Unbal.dss
  tests/data/big_cases/opendss/ieee_8500node/Run_RecloserSiting.DSS
  tests/data/big_cases/opendss/ieee_8500node/TplxFaultrate.dss
  tests/data/big_cases/opendss/ieee_8500node/Transformers.dss
  tests/data/big_cases/opendss/ieee_8500node/Triplex_Linecodes.dss
  tests/data/big_cases/opendss/ieee_8500node/Triplex_Lines.DSS
  tests/data/big_cases/opendss/ieee_8500node/UnbalancedLoads.DSS
  tests/data/big_cases/opendss/ieee_8500node/WireData.dss
  tests/data/big_cases/opendss/ieee_8500node/buscoord.dss
  tests/data/big_cases/opendss/ieee_8500node/master.dss
  tests/test_reader.py
Labels: documentation, enhancement

#66 Json parsers
  ditto/readers/json/read.py
  ditto/writers/json/write.py
  tests/test_json_parsers.py
Labels: BugFix

#53 Add metrics.md (still needs modifications)
  ditto/metrics/network_analysis.py
  docs/metrics.md
  docs/modifications.md
Labels: documentation, enhancement

#82 Minor readwrite bugs
  ditto/network/network.py
  ditto/readers/cyme/read.py
  ditto/readers/gridlabd/read.py
  ditto/writers/cyme/write.py
  ditto/writers/demo/write.py
  ditto/writers/ephasor/write.py
Labels: BugFix

#83 Load connected kva
  ditto/metrics/network_analysis.py
  ditto/models/load.py
  ditto/readers/cyme/read.py
Labels: BugFix, validation

#85 Bugfix unit
  ditto/metrics/network_analysis.py
  ditto/readers/cyme/read.py
Labels: BugFix

#87 Add ditto cli
  docs/cli-examples.md
  examples/README.md
  setup.py
  tests/test_ditto_cli.py
Labels: BugFix

#91 Change Winding type from Core to Shell form in Cyme writer
  ditto/writers/cyme/write.py
Labels: BugFix

#92 Unused condIDs are set to None instead of DEFAULT
  ditto/writers/cyme/write.py
Labels: BugFix

#93 Overhead line setting by phase configuration transition
  ditto/modify/system_structure.py
  ditto/writers/cyme/write.py
Labels: BugFix

#89 Cli jsonize feature
  ditto/cli.py
  ditto/converter.py
  ditto/readers/json/__init__.py
  ditto/readers/json/read.py
  ditto/writers/json/__init__.py
  ditto/writers/json/write.py
  setup.py
  tests/test_json_parsers.py
Labels: enhancement

#95 Compute nominal voltages in the OpenDSS reader
  ditto/readers/opendss/read.py
Labels: enhancement

#101 Add is_substation to objects
  ditto/models/capacitor.py
  ditto/models/line.py
  ditto/models/load.py
  ditto/models/node.py
  ditto/models/powertransformer.py
  ditto/models/regulator.py
  ditto/models/storage.py
Labels: API Modification Request

#100 Metrics cli
  ditto/cli.py
  ditto/converter.py
  ditto/metric_computer.py
  tests/read_dss_13node.json
  tests/test_ditto_cli.py
Labels: enhancement

#98 Fix IDs for Networks, Sources, and Headnodes in Cyme writer
  ditto/writers/cyme/write.py
Labels: BugFix, enhancement

#94 Fix docstrings
  ditto/converter.py
  ditto/metrics/network_analysis.py
  ditto/modify/modify.py
  ditto/modify/system_structure.py
  ditto/network/network.py
  ditto/readers/abstract_reader.py
  ditto/readers/cyme/read.py
  ditto/readers/demo/read.py
  ditto/readers/gridlabd/read.py
  ditto/readers/json/read.py
  ditto/readers/opendss/read.py
  ditto/store.py
  ditto/writers/abstract_writer.py
  ditto/writers/cyme/write.py
  ditto/writers/demo/write.py
  ditto/writers/ephasor/write.py
  ditto/writers/gridlabd/write.py
  ditto/writers/json/write.py
  ditto/writers/opendss/write.py
  examples/epri_j1_opendss_to_cyme.py
  examples/ieee_123node_cyme_to_opendss.py
  examples/ieee_123node_gridlabd_to_opendss.py
  examples/ieee_8500_opendss_to_cyme.py
Labels: enhancement
