Repository NREL/ditto, pull requests merged in 2018-10, with the labels that each got.

#192 Start of Unit Tests for Cyme Reader
  tests/readers/__init__.py
  tests/readers/cyme/__init__.py
  tests/readers/cyme/test_capacitor_connection_mapping.py
  tests/readers/cyme/test_phase_mapping.py
Labels: enhancement

#196 Add tests of CYME connection configuration mapping
  ditto/readers/cyme/read.py
  tests/readers/cyme/test_connection_configuration_mapping.py
Labels: enhancement

#194 Test for Cyme Transformer Connection Mapping
  tests/readers/cyme/test_transformer_connection_mapping.py
Labels: enhancement

#199 Add simple Capacitor writing test
  tests/writers/__init__.py
  tests/writers/opendss/capacitors/test_capacitor_writing.py
Labels: enhancement

#197 Synergi reader length unit parser
  ditto/readers/synergi/length_units.py
  ditto/readers/synergi/read.py
  tests/readers/synergi/__init__.py
  tests/readers/synergi/test_unit_converter.py
Labels: enhancement

#207 Remove eval json reader
  ditto/readers/json/read.py
  ditto/writers/json/write.py
Labels: enhancement

#200 Recent Synergi bugfixes merged to master
  ditto/readers/cyme/read.py
  ditto/readers/synergi/read.py
  ditto/writers/opendss/write.py
  tests/test_opendss_writer.py
Labels: BugFix, enhancement

#216 indent json
  ditto/writers/json/write.py
Labels: enhancement

#217 Change json structure
  ditto/readers/json/read.py
  ditto/writers/json/write.py
Labels: enhancement

#220 Sort when writing to JSON
  ditto/writers/json/write.py
Labels: enhancement

#218 Updating for compatability with V1.6
  ditto/writers/ephasor/write.py
Labels: enhancement

#221 Fix emergency ampacity bug
  ditto/readers/cyme/read.py
  ditto/readers/dew/read.py
  ditto/readers/dew/read_new.py
  ditto/readers/gridlabd/read.py
  ditto/readers/opendss/read.py
  ditto/writers/opendss/write.py
Labels: BugFix

#219 Persistence tests
  tests/data/small_cases/cyme/ieee_13node/load.txt
  tests/persistence/data/small_cases/cyme/ieee_13node/Model.json
  tests/persistence/data/small_cases/cyme/ieee_4node/Model.json
  tests/persistence/data/small_cases/opendss/ieee_13node/Model.json
  tests/persistence/data/small_cases/opendss/ieee_4node/Model.json
  tests/persistence/test_persistence.py
  tests/persistence/update_json.py
Labels: enhancement
