Repository NREL/ditto, pull requests merged in 2018-08, with the labels that each got.

#154 Synergi reader
  ditto/converter.py
  ditto/readers/synergi/__init__.py
  ditto/readers/synergi/db_parser.py
  ditto/readers/synergi/read.py
  ditto/writers/opendss/write.py
  setup.py
Labels: New Parser

#165 Synergi reader dev
  ditto/readers/synergi/read.py
Labels: enhancement

#166 Transformer settings table
  ditto/converter.py
  ditto/metrics/network_analysis.py
  ditto/models/photovoltaic.py
  ditto/modify/system_structure.py
  ditto/network/network.py
  ditto/readers/cyme/read.py
  ditto/readers/opendss/read.py
  ditto/writers/cyme/write.py
  ditto/writers/opendss/write.py
  tests/data/small_cases/cyme/ieee_13node/loads.txt
Labels: API Modification Request, BugFix, enhancement

#167 PowerSource-->Photovoltaic
  ditto/readers/json/read.py
  ditto/readers/synergi/read.py
  ditto/writers/ephasor/write.py
Labels: Do Not Merge

#168 Add reference height to conductors in the geometries.
  ditto/readers/synergi/read.py
Labels: BugFix

#169 Add sources synergi reader
  ditto/readers/synergi/read.py
Labels: enhancement

#170 Add switching devices synergi reader
  ditto/readers/synergi/read.py
Labels: enhancement

#171 Add is sectionalizer to wires
  ditto/models/line.py
  ditto/models/wire.py
Labels: API Modification Request, BugFix

#176 Opendss reader geometries bugfix
  ditto/readers/opendss/read.py
  setup.py
  tests/data/ditto-validation/opendss/linegeometries/Master.dss
  tests/test_opendss_reader.py
Labels: BugFix

#178 Enable multiple headers to be used for the same object
  ditto/readers/cyme/read.py
Labels: enhancement

#174 Add per unit to source
  ditto/models/power_source.py
  ditto/readers/opendss/read.py
  ditto/readers/synergi/read.py
  ditto/writers/opendss/write.py
Labels: API Modification Request, enhancement
